### ISSUE TITLE
An SSL error has occurred and a secure connection to the server cannot be made.

### ISSUE THREAD

**Issue by linktoming** [LiveUI/iJenkins#35]
When I add a Jenkins server that using https, I got this error when trying to connect to it.

Screenshot below:
![screen shot 2014-09-26 at 12 21 32 pm](https://cloud.githubusercontent.com/assets/446371/4415910/bc0bf920-4534-11e4-9039-6e81d8ee7f29.png)

**Comment by linktoming** [comment]
Sadly I'm not sure since I'm not the maintainer of the Jenkins server.

**Comment by uday1955** [comment]
When I used https option, app crashed and it works fine with http. We use https when we access it on the browser

**Comment by rafiki270** [comment]
The error is coming from AFNetworking I would say (or even the iOS itself) ... the issue with having both port as well as the https switch should be addressed tho ...
