### ISSUE TITLE
Support for Jenkins installations w/ Github OAuth Plugin

### ISSUE THREAD

**Issue by elloboblanco** [LiveUI/iJenkins#48]
My repo utilizes Github OAuth. Can you support this in the future? https://wiki.jenkins-ci.org/display/JENKINS/Github+OAuth+Plugin

**Comment by maxromanovsky** [comment]
+1 on that!

**Comment by rafiki270** [comment]
Anybody would be willing to pick this up?

**Comment by JulianKingman** [comment]
+1, is there a workaround to sign in on the app?

**Comment by dsbaars** [comment]
I'd love this too, I noticed at the authentication section the subtext _Or API token_. Maybe there is something possible there? On GitHub you can also login using your regular username and the API token as password which works around two-factor auth.

**Comment by JulianKingman** [comment]
Thanks @dsbaars, even knowing where to find the API token is handy, I'm logged in now.

**Comment by ssbarnea** [comment]
So what is the workaround for using it with github auth enabled?

**Comment by JulianKingman** [comment]
What @dsbaars said. Just use the API token in place of the password.

**Comment by kanuku** [comment]
+1

**Comment by ssbarnea** [comment]
@kanuku In the future, please use github reactions instead of +1 to avoid comment and notification spam.
