### ISSUE TITLE
Support for longer job names

### ISSUE THREAD

**Issue by ogt00l** [LiveUI/iJenkins#49]
In portrait mode, the job names are truncated and appended with "..."

When rotating to landscape mode, there is much more screen realestate to support a longer name, however the same length is shown as in portrait mode. It would be great to use the extra space in landscape.

Another improvement could be utilising 3D touch to show the an insight into the job from the main job list menu (full name, last build date, last successful build date etc)

**Comment by rafiki270** [comment]
we'll look into the long names, that is definitely a bug but don't think we'll get into the force touch unless any developer would feel like creating something like that?
