### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by borbamartin** [LiveUI/iJenkins#55]
Login dialog pops up with credentials stored. When trying to build it keeps asking for credentials, even after inputting them again.

iOS 9.3 (I know it says it's for iOS7)

Port to 9.3 anytime soon? :)

**Comment by rafiki270** [comment]
hi, I haven't had this issue yet, could you let me know some server details please? meaning OS, jenkins ver, etc ...

**Comment by borbamartin** [comment]
Jenkins ver. 1.607 on Ubuntu 12.04

**Comment by bjoernHeneka** [comment]
Have the Same issue. Jenkins 2.3 with official docker image from Jenkins

**Comment by stefanprodan** [comment]
Same problem on Jenkins ver. 2.22 running in Docker. My authorization setting is the default: Logged-in users can do anything.

**Comment by leelavery** [comment]
Same issue here Jenkins v 2.23 and iOS 10...

**Comment by kiichi** [comment]
Same problem with Jenkins V2.4.0 and iOS 10 iPad version of the iJenkins app Version: 1.4.1

**Comment by edge2012** [comment]
Same issue with Jenkins 2.7.4 and iOS 10.3
