### ISSUE TITLE
Support folders

### ISSUE THREAD

**Issue by hypery2k** [LiveUI/iJenkins#58]
Support for the folder plugin, which is included in Jenkins 2 would be great. Currently no jobs are recognized when they are in a folder

**Comment by hypery2k** [comment]
Any news?

**Comment by chandlerhuff** [comment]
@hypery2k I added top level folder support to my fork [here](https://github.com/chandlerhuff/iJenkins) with some other modifications.

**Comment by hypery2k** [comment]
@chandlerhuff cool. I will take your fork and build a package for the AppStore ;)

**Comment by glopezgrassi** [comment]
+1

@hypery2k did you have the chance to build the app with folder support?

Thanks!

**Comment by hypery2k** [comment]
Only with top level folder support

**Comment by muya** [comment]
I found a workaround to the folders issue. If you don't mind, you can set up multiple "Servers", then edit the "Path" field to the path of your folder. E.g. if you have a job at: http://1.1.1.1:8080/view/Folder1/job/Folder2/job/Folder3/, you can set the Path field of the config to: `/view/Folder1/job/Folder2/job/Folder3/` - in this case, the jobs under "Folder3" will show up

If you are setting up Jenkins for important stuff, it might be worth the effort to set up your most important jobs this way

**Comment by chandlerhuff** [comment]
@muya my [fork](https://github.com/chandlerhuff/iJenkins) now supports multilevel folders

**Comment by EltonAlvess** [comment]
This issue has been published in appstore?
